### ISSUE TITLE
May need encapsulation - User.documents

### ISSUE THREAD

**Issue by Shakirovrrr** [lenargum/libraryProject#2]
In [User.java](https://github.com/lenargum/libraryProject/blob/User-Documents-Connection/src/User.java) `document` field is public. Shouldn't it be encapsulated?

```Java
. . .
private String phoneNumber;
private int id;

public List<Document> documents = new LinkedList<>();  // Here
. . .
```

**Comment by gafmn** [comment]
I fixed it
